# Generated by Django 4.0.3 on 2022-04-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_users_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='image',
            new_name='photo',
        ),
    ]
