# Generated by Django 4.0.3 on 2022-04-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_image_users_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='photo',
            new_name='image',
        ),
    ]
